### ISSUE TITLE
Run Again doesn't recognize changes

### ISSUE THREAD

**Issue by gvn** [joshvarner/JSLint.tmbundle#1]
First off, thanks for making this tool!

When I click "Run Again" after making a change to the code and saving it, the changes don't reflect inside the validation results. I have to close the window and re-run. This is cumbersome for fixing errors.

Is there any way you can fix the tool to recognize that the code has changed since the last time validation was run?

**Comment by joshvarner** [comment]
Thanks for the feedback. Try pulling the commit I just pushed and see if that works out for you.

Commit: 8f057b31c61d950ba4cb33a44921de828e7919a0

**Comment by gvn** [comment]
Awesome! Totally works now!
